### ISSUE TITLE
Add sunrpc_tcp and sunrpc_udp to UNIX EntityStateEndpointType and EntityItemEndpointType

### ISSUE THREAD

**Issue by tannerdc** [OVALProject/Sandbox#140]
The EntityStateEndpointType and EntityItemEndpointType currently allow stream, dgram, raw, seqpacket, tli, and empty string.  However, to properly support the inetd_test on AIX we need to add sunrpc_tcp and sunrpc_udp.  

This change will not affect other versions of UNIX.

                    <xsd:enumeration value="sunrpc_tcp">
                         <xsd:annotation>
                              <xsd:documentation>The sunrpc_tcp value is used to describe all SUNRPC TCP endpoints.</xsd:documentation>
                         </xsd:annotation>
                    </xsd:enumeration>
                    <xsd:enumeration value="sunrpc_udp">
                         <xsd:annotation>
                              <xsd:documentation>The sunrpc_udp value is used to describe all SUNRPC UDP endpoints.</xsd:documentation>
                         </xsd:annotation>
                    </xsd:enumeration>

**Comment by solind** [comment]
It appears these were added to the language in 5.11.1.
