### ISSUE TITLE
Investigate the need for a dpkg_evr_string datatype

### ISSUE THREAD

**Issue by drothenberg** [OVALProject/Sandbox#142]
This would alleviate concerns between differences in RPM and dpkg version comparisons. Current documentation (rpminfo_state evr) points to rpmvercmp as the algorithm to handle evr_string entities and should be updated, while other documentation (dpkginfo_state evr) does not indicate an algorithm.

Example:
On RedHat, 10a > a10
On Debian, 10a < a10

**Comment by solind** [comment]
This was done in 5.11.1
