### ISSUE TITLE
add support for a win-def:license_test

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Sandbox#2]
We should look into adding support for a win-def:license_test that exposes the NtQueryLicenseValue and ZwQueryLicenseValue functions from NTDLL.DLL in Windows version 6.0 and higher to see if it can provide a better mechanism for accessing the license data on a Windows system rather than using the existing win-def:registry_test. 

Please see the following oval-developer-list post for more information.

http://making-security-measurable.1364806.n2.nabble.com/Accessing-Windows-license-data-tp6769688p6769688.html

**Comment by solind** [comment]
We added this in 5.11.
