### ISSUE TITLE
improve the usability and capabilities of the plist510_test

### ISSUE THREAD

**Issue by djhaynes** [OVALProject/Sandbox#22]
There have been two proposals to improve the usability and capabilities of the existing plist510_test. This will require adding a new plist511_test.  So far, there have been two proposals:

1) Use a key record entity, where each field represents a level and a key, to select a preference key value.

2) Use a xpath entity to drive the collection of a preference key value. 

Please see the following oval-developer-list post for additional information. 

http://making-security-measurable.1364806.n2.nabble.com/Proposed-modification-to-the-plist510-test-in-the-Apple-Macintosh-Schema-tp7471496p7471496.html

**Comment by solind** [comment]
See implementation of plist11_test in 5.11.2.
